### PR TITLE
Intellij settings files removed

### PR DESCRIPTION
**Pull request by r3dol**

### CODE REVIEW

**Review by Norton1337 — APPROVED** [review]
looks good

**Comment by r3dol** [comment]
> looks good

u mean lgtm?

**Comment by Norton1337** [comment]
> > looks good
> 
> u mean lgtm?

mb. lgtm!

**Comment by r3dol** [comment]
> > > looks good
> > 
> > 
> > u mean lgtm?
> 
> mb. lgtm!

prod to the moon 🚀

**Comment by silvidae1** [comment]
Thank you very much

**Comment by Norton1337** [comment]
Na boa meu nobre

**Comment by r3dol** [comment]
> Thank you very much


> Na boa meu nobre

- na boa meu nobre

**Pull request merged**
